name: Release

on:
  pull_request:
    # types:
    #   - opened
    branches:
      - main

jobs:
  release:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 # ðŸ‘ˆ Required to retrieve git history
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      # - run: npm set '//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}'
      # - run: npm ci
      - name: Release
        run: |
          git config user.email me@boonya.info
          git config user.name bot
          npx lerna version prerelease --yes \
            --conventional-commits \
            --create-release github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
