name: Publish ðŸšš

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  test:
    name: "Test ðŸ‘®ðŸ½â€â™‚ï¸"
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    needs: test
    runs-on: ubuntu-latest
    name: Publishing package ðŸš€
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com/
          scope: "@boonya"
      - run: npm ci
      - run: npm run build
      - if: github.event_name == 'release'
        name: "Release"
        run: |
          cd build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name != 'release'
        name: "Publishing"
        run: |
          cd build
          version=$(jq -r .version package.json)
          echo $(jq ".version = \"$version-$GITHUB_SHA\"" package.json) > package.json
          npm publish --tag $GITHUB_SHA
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
